# Generated by Django 4.1.3 on 2023-03-14 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmenttask',
            options={'permissions': (('can_manage_departmnet_task', 'Can Manage Department Task'),)},
        ),
    ]
