# Generated by Django 4.1.3 on 2023-01-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_lead_first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Team Lead First Name'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_lead_last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Team Lead Last Name'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_lead_username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Team Lead Username'),
        ),
    ]
