# Generated by Django 4.1.3 on 2023-01-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_team_lead_first_name_team_team_lead_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_lead_first_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_lead_last_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_lead_username',
        ),
        migrations.AddField(
            model_name='team',
            name='team_lead_full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Team Lead Username'),
        ),
    ]
