# Generated by Django 4.1.3 on 2023-02-01 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0003_remove_team_team_lead_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_lead_username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Team Lead Username'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
