# Generated by Django 4.1.3 on 2023-02-02 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_task_has_subtask'),
        ('team', '0006_alter_teammember_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_team', to='task.task', verbose_name='Task')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_tasks', to='team.team', verbose_name='Team')),
            ],
        ),
    ]
