# Generated by Django 4.1.3 on 2023-03-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_alter_teamtasks_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
