# Generated by Django 4.1.3 on 2023-03-07 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0010_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_lead_full_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_lead_username',
        ),
        migrations.AlterField(
            model_name='team',
            name='team_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='leading_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
