# Generated by Django 4.1.3 on 2023-03-18 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_alter_task_task_type'),
        ('team', '0014_alter_teamtasks_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamtasks',
            name='id',
        ),
        migrations.AlterField(
            model_name='teamtasks',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='task_team', serialize=False, to='task.task', verbose_name='Task'),
        ),
    ]
