# Generated by Django 4.1.3 on 2023-03-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_remove_teamtasks_id_alter_teamtasks_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtasks',
            name='root_task',
            field=models.BooleanField(default=False, verbose_name='Team root task'),
        ),
    ]
