# Generated by Django 4.1.3 on 2022-12-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(max_length=200, verbose_name='Email Subject')),
                ('email_body', models.TextField(verbose_name='Email Body')),
                ('email_to', models.CharField(max_length=1000, verbose_name='Email To')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Email Sending Time')),
                ('email_status', models.CharField(choices=[('SUC', 'Email Success'), ('FIL', 'Email Failure')], max_length=3, verbose_name='Email Status')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
