# Generated by Django 4.1.3 on 2022-12-11 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('emailservice', '0002_alter_emailhistory_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailhistory',
            name='email_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email', to='django_celery_results.taskresult', verbose_name='Email Core'),
        ),
        migrations.AlterField(
            model_name='emailhistory',
            name='email_status',
            field=models.CharField(choices=[('SUC', 'Email Success'), ('FIL', 'Email Failure'), ('STR', 'Email Send Started')], max_length=3, verbose_name='Email Status'),
        ),
    ]
