# Generated by Django 4.1.3 on 2022-11-06 11:04

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', authentication.models.CustomUserManager()),
            ],
        ),
    ]
