# Generated by Django 4.1.3 on 2023-01-29 05:42

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=authentication.models.user_photo_upload_path, verbose_name='User photo'),
        ),
    ]
