# Generated by Django 4.1.3 on 2023-01-29 06:08

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.user_photo_upload_path, verbose_name='User photo'),
        ),
    ]
