# Generated by Django 4.1.3 on 2023-01-10 06:57

from django.db import migrations, models
import goal.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Quarter Goal Title')),
                ('description', models.TextField(verbose_name='Goal Description')),
                ('year', models.IntegerField(validators=[goal.validators.validate_year], verbose_name='Goal Year')),
                ('quarter', models.CharField(max_length=10, verbose_name='Year Quarter')),
                ('review_status', models.CharField(max_length=10, verbose_name='Goal Review Status')),
                ('review', models.TextField(verbose_name='Review under goal')),
                ('completion', models.IntegerField(validators=[goal.validators.validate_completion], verbose_name='Goal total completion on percentage')),
            ],
            options={
                'permissions': (('can_add_review', 'Can Add Review'), ('can_change_status', 'Can Change Status')),
            },
        ),
    ]
