# Generated by Django 4.1.3 on 2023-01-10 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0010_departmentmember_one_head_per_department'),
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='Department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='department_goals', to='department.department', verbose_name='Department'),
            preserve_default=False,
        ),
    ]
