# Generated by Django 4.1.3 on 2023-01-10 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_goal_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='Department',
            new_name='department',
        ),
    ]
