# Generated by Django 4.1.3 on 2023-01-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0003_rename_department_goal_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], max_length=10, verbose_name='Year Quarter'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='review_status',
            field=models.CharField(choices=[('ACC', 'Accepted'), ('Pen', 'Pending')], max_length=10, verbose_name='Goal Review Status'),
        ),
    ]
