# Generated by Django 4.1.3 on 2023-03-06 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goal', '0007_alter_goal_quarter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'permissions': (('can_change_status', 'Can Change Status'),)},
        ),
        migrations.RemoveField(
            model_name='goal',
            name='review',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='review_status',
        ),
        migrations.AddField(
            model_name='goal',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='created_goals', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('ACC', 'Accepted'), ('Pen', 'Pending'), ('REJ', 'Rejected')], default='Pen', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='quarter',
            field=models.IntegerField(choices=[(1, 'Quarter 1'), (2, 'Quarter 2'), (3, 'Quarter 3'), (4, 'Quarter 4')], verbose_name='Goal Quarter'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='Review')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Reviewed at')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='goal.goal', verbose_name='Goal')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='added_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by')),
            ],
        ),
        migrations.CreateModel(
            name='GoalLastEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='Edited at')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goal_edits', to=settings.AUTH_USER_MODEL, verbose_name='Edited by')),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='goal.goal', verbose_name='Goal')),
            ],
        ),
    ]
