# Generated by Django 4.1.3 on 2023-03-07 06:15

from django.db import migrations, models
import goal.validators


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0008_alter_goal_options_remove_goal_review_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'permissions': (('can_change_status', 'Can Change Status'), ('cna_view_all_goals', 'Can View All Goals'))},
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='quarter',
            field=models.IntegerField(choices=[(1, 'Quarter 1'), (2, 'Quarter 2'), (3, 'Quarter 3'), (4, 'Quarter 4')], verbose_name='Quarter'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='year',
            field=models.IntegerField(validators=[goal.validators.validate_year], verbose_name='Year'),
        ),
    ]
