# Generated by Django 4.1.3 on 2023-03-22 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0009_alter_goal_options_alter_goal_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'permissions': (('can_change_status', 'Can Change Status'), ('can_view_all_goals', 'Can View All Goals'))},
        ),
    ]
