# Generated by Django 4.1.3 on 2023-01-18 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Task title')),
                ('description', models.TextField(verbose_name='Task description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Task creation time')),
                ('last_date', models.DateTimeField(verbose_name='Task submission dadeline')),
                ('approved_by_dept_head', models.BooleanField(default=False, verbose_name='Approved by department head')),
                ('status', models.CharField(choices=[('PEN', 'Pending task'), ('DUE', 'Due task'), ('COM', 'Completed task')], max_length=3, verbose_name='Task status')),
                ('priority', models.CharField(choices=[('URG', 'Urgent priority'), ('HGH', 'High priority'), ('NRM', 'Normal priority'), ('LOW', 'Low priority')], max_length=3, verbose_name='Task priority')),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Task assign to')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Task created by user')),
            ],
        ),
    ]
