# Generated by Django 4.1.3 on 2023-01-18 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import task.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=task.models.task_attachment_upload_path, verbose_name='Task attachment')),
                ('attached_at', models.DateTimeField(auto_now_add=True, verbose_name='File attached at')),
                ('attached_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_files', to=settings.AUTH_USER_MODEL, verbose_name='Task attachments')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attachments', to='task.task', verbose_name='Task attachments')),
            ],
        ),
    ]
