# Generated by Django 4.1.3 on 2023-01-18 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskattachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_parent', to='task.task', verbose_name='Task child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_childs', to='task.task', verbose_name='Task parent')),
            ],
        ),
    ]
