# Generated by Django 4.1.3 on 2023-01-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_tasktree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assign_to',
        ),
    ]
