# Generated by Django 4.1.3 on 2023-01-18 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0004_remove_task_assign_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to=settings.AUTH_USER_MODEL, verbose_name='User assigned task')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned_to', to='task.task', verbose_name='Task assigned to')),
            ],
        ),
    ]
