# Generated by Django 4.1.3 on 2023-01-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_userstasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': (('can_approve_disapprove_task', 'Can Approve Or Disapprove Tasks'),)},
        ),
    ]
