# Generated by Django 4.1.3 on 2023-01-18 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0007_alter_userstasks_options_userstasks_user_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstasks',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userstasks',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_assigned_to', to='task.task', verbose_name='Task'),
        ),
    ]
