# Generated by Django 4.1.3 on 2023-01-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_userstasks_assigned_to_alter_userstasks_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by_user_fullname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Created by user full name'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by_user_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Created by user  username'),
        ),
    ]
