# Generated by Django 4.1.3 on 2023-01-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_task_created_by_user_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('URG', 'Urgent priority'), ('HGH', 'High priority'), ('NRM', 'Normal priority'), ('LOW', 'Low priority')], default='LOW', max_length=3, verbose_name='Task priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending task'), ('DUE', 'Due task'), ('COM', 'Completed task')], default='PEN', max_length=3, verbose_name='Task status'),
        ),
    ]
