# Generated by Django 4.1.3 on 2023-01-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='approved_by_dept_head',
        ),
        migrations.AddField(
            model_name='task',
            name='approval_status',
            field=models.CharField(choices=[('APP', 'Approved'), ('PEN', 'Pending'), ('REJ', 'Rejected')], default='PEN', max_length=3, verbose_name='Task approval by department head'),
        ),
    ]
