# Generated by Django 4.1.3 on 2023-01-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_alter_task_options_alter_userstasks_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending task'), ('DUE', 'Due task'), ('COM', 'Completed task'), ('SUB', 'Sumitted Task')], default='PEN', max_length=3, verbose_name='Task status'),
        ),
    ]
