# Generated by Django 4.1.3 on 2023-01-25 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0013_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachments',
            name='attached_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_files', to=settings.AUTH_USER_MODEL, verbose_name='Attached by'),
        ),
        migrations.AlterField(
            model_name='taskattachments',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attachments', to='task.task', verbose_name='Task'),
        ),
    ]
