# Generated by Django 4.1.3 on 2023-01-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_task_is_assigned_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='has_subtask',
            field=models.BooleanField(default=False, verbose_name='Task has any subtask'),
        ),
    ]
