# Generated by Django 4.1.3 on 2023-02-23 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import task.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0016_task_has_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='user_created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Task created by user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='last_date',
            field=models.DateTimeField(validators=[task.validators.validate_task_submission_last_date], verbose_name='Task submission dadeline'),
        ),
    ]
