# Generated by Django 4.1.3 on 2023-02-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_alter_task_created_by_alter_task_last_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_by_user_fullname',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by_user_username',
        ),
    ]
