# Generated by Django 4.1.3 on 2023-02-23 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_remove_task_created_by_user_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstasks',
            name='user_full_name',
        ),
        migrations.RemoveField(
            model_name='userstasks',
            name='user_username',
        ),
    ]
