# Generated by Django 4.1.3 on 2023-03-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_alter_taskattachments_attached_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Task description'),
        ),
    ]
