# Generated by Django 4.1.3 on 2023-03-19 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_alter_task_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstasks',
            name='id',
        ),
        migrations.AlterField(
            model_name='userstasks',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='task_assigned_to', serialize=False, to='task.task', verbose_name='Task'),
        ),
    ]
