# Generated by Django 4.1.3 on 2023-02-07 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0012_alter_departmentmember_designation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Project Title')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('deadline', models.DateField(verbose_name='Project Deadline')),
                ('budget', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Project Budget')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_projects', to='department.department', verbose_name='Department Projects')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager')),
                ('project_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Owner')),
            ],
        ),
    ]
