# Generated by Django 4.1.3 on 2023-02-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PAU', 'Paused'), ('ACT', 'Active'), ('FIN', 'Active')], default='PAU', max_length=3, verbose_name='Project Status'),
        ),
    ]
