# Generated by Django 4.1.3 on 2023-02-07 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSchemaLessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_title', models.CharField(max_length=200, verbose_name='Department Title')),
                ('project_owner_fullname', models.CharField(max_length=200, verbose_name='Project Owner Fullname')),
                ('project_manager_fullname', models.CharField(max_length=200, verbose_name='Project Manager Fullname')),
                ('project_owner_username', models.CharField(max_length=200, verbose_name='Project Manager Username')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schemaless_data', to='project.project', verbose_name='Schemaless Data')),
            ],
        ),
    ]
