# Generated by Django 4.1.3 on 2023-02-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectschemalessdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectschemalessdata',
            name='project_manager_username',
            field=models.CharField(default='', max_length=200, verbose_name='Project Manager Username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectschemalessdata',
            name='project_owner_username',
            field=models.CharField(max_length=200, verbose_name='Project Owner Username'),
        ),
    ]
