# Generated by Django 4.1.3 on 2023-02-08 08:15

from django.db import migrations, models
import project.validators


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0012_alter_departmentmember_designation_and_more'),
        ('project', '0004_projectschemalessdata_project_manager_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(validators=[project.validators.validate_project_deadline], verbose_name='Project Deadline'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('department', 'title')},
        ),
    ]
