# Generated by Django 4.1.3 on 2023-02-08 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_project_manager_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('can_maintain_project', 'Can Manage A Project'), ('can_own_project', 'Can Own Project'), ('can_view_all_project', 'Can View All Projects'))},
        ),
    ]
