# Generated by Django 4.1.3 on 2023-02-08 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0007_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='managed_projects', to=settings.AUTH_USER_MODEL, validators=[project.validators.validate_project_manager_permission], verbose_name='Project Manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='owned_projects', to=settings.AUTH_USER_MODEL, validators=[project.validators.validate_project_owner_permission], verbose_name='Project Owner'),
        ),
    ]
