# Generated by Django 4.1.3 on 2023-02-09 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0009_alter_project_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='project.project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMemberSchemaLessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=500, verbose_name='Project Title')),
                ('member_username', models.CharField(max_length=200, verbose_name='Member Username')),
                ('member_fullname', models.CharField(max_length=200, verbose_name='Member Fullname')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_member_schemaless_data', to='project.projectmember', verbose_name='Project')),
            ],
        ),
    ]
