# Generated by Django 4.1.3 on 2023-02-15 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models.project_models
import project.validators


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_task_has_subtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0009_alter_project_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectschemalessdata',
            name='members',
            field=models.ManyToManyField(related_name='user_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Members'),
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='project.project', verbose_name='Project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_project', to='task.task', validators=[project.validators.validate_project_task_type], verbose_name='Task')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=project.models.project_models.project_attachment_upload_path, verbose_name='Project Attachment')),
                ('attached_at', models.DateTimeField(auto_now_add=True, verbose_name='Attached At')),
                ('attached_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attachments_on_project', to=settings.AUTH_USER_MODEL, verbose_name='Attached By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_attachments', to='project.project', verbose_name='Project')),
            ],
        ),
    ]
