# Generated by Django 4.1.3 on 2023-02-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_projectschemalessdata_members_projecttask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectschemalessdata',
            name='members',
        ),
    ]
