# Generated by Django 4.1.3 on 2023-02-15 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0011_remove_projectschemalessdata_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='user_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Members'),
        ),
    ]
