# Generated by Django 4.1.3 on 2023-02-12 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models.project_models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0011_alter_projectmember_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=project.models.project_models.project_attachment_upload_path, verbose_name='Project Attachment')),
                ('attached_at', models.DateTimeField(auto_now_add=True, verbose_name='Attached At')),
                ('attached_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='attachments_on_project', to=settings.AUTH_USER_MODEL, verbose_name='Attached By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_attachments', to='project.project', verbose_name='Project')),
            ],
        ),
    ]
