# Generated by Django 4.1.3 on 2023-03-16 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_project_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectSchemaLessData',
        ),
    ]
