# Generated by Django 4.1.3 on 2023-02-12 11:36

from django.db import migrations, models
import django.db.models.deletion
import project.validators


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_task_has_subtask'),
        ('project', '0012_projectattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='project.project', verbose_name='Project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_project', to='task.task', validators=[project.validators.validate_project_task_type], verbose_name='Task')),
            ],
        ),
    ]
