# Generated by Django 4.1.3 on 2023-02-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_projecttask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectMemberSchemaLessData',
        ),
    ]
