# Generated by Django 4.1.3 on 2023-03-27 06:08

from django.db import migrations, models
import django.db.models.deletion
import project.validators


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0023_remove_userstasks_id_alter_userstasks_task'),
        ('project', '0015_remove_projecttask_id_alter_projecttask_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='task_project', serialize=False, to='task.task', validators=[project.validators.validate_project_task_type], verbose_name='Task'),
        ),
    ]
