# Generated by Django 4.1.3 on 2022-12-12 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Department Name')),
                ('description', models.TextField(verbose_name='Department Description')),
            ],
        ),
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Designation Title')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_designations', to='department.department', verbose_name='Department Designations')),
            ],
            options={
                'unique_together': {('department', 'title')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='department.designations', verbose_name='designated_member')),
                ('Member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_departments', to=settings.AUTH_USER_MODEL, verbose_name='Member')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_members', to='department.department', verbose_name='Department')),
            ],
        ),
    ]
