# Generated by Django 4.1.3 on 2022-12-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(default='temp', unique=True, verbose_name='Department Name SLug'),
            preserve_default=False,
        ),
    ]
