# Generated by Django 4.1.3 on 2022-12-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_rename_member_departmentmember_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentmember',
            old_name='Designation',
            new_name='designation',
        ),
    ]
