# Generated by Django 4.1.3 on 2022-12-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_rename_designation_departmentmember_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmember',
            name='department_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Department Name'),
        ),
        migrations.AddField(
            model_name='departmentmember',
            name='designation_title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Designation Title'),
        ),
        migrations.AddField(
            model_name='departmentmember',
            name='member_full_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Department Member Full name'),
        ),
    ]
