# Generated by Django 4.1.3 on 2022-12-29 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_departmentmember_department_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='department_head', to='department.department', verbose_name='Department Head')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='head_of_department', to='department.departmentmember', verbose_name='Head Of Department')),
            ],
        ),
    ]
