# Generated by Django 4.1.3 on 2022-12-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_departmenthead'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmember',
            name='is_head',
            field=models.BooleanField(default=False, verbose_name='Department Head'),
        ),
        migrations.DeleteModel(
            name='DepartmentHead',
        ),
    ]
