# Generated by Django 4.1.3 on 2022-12-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_departmenthead'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentHead',
        ),
    ]
