# Generated by Django 4.1.3 on 2022-12-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_delete_departmenthead'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='departmentmember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_head', True)), fields=('department',), name='one_head_per_department'),
        ),
    ]
