# Generated by Django 4.1.3 on 2023-01-15 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0010_departmentmember_one_head_per_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmember',
            name='id',
        ),
        migrations.AlterField(
            model_name='departmentmember',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_departments', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Member'),
        ),
    ]
