# Generated by Django 4.1.3 on 2023-01-15 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0011_remove_departmentmember_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmember',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='department.designations', verbose_name='designated_members'),
        ),
        migrations.AlterField(
            model_name='departmentmember',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_department', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Member'),
        ),
    ]
